# Generated by Django 5.0.4 on 2024-04-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='genre',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='quiz.genres'),
        ),
    ]
