# Generated by Django 5.0.4 on 2024-04-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizzes_genre_quizzes_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quizzes'),
        ),
    ]
