# Generated by Django 5.0.4 on 2024-04-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_questions_quiz_alter_questions_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
    ]
