# Generated by Django 5.0.4 on 2024-04-08 14:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_questions_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profiles',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='quiz_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='quiz_name',
            new_name='name',
        ),
    ]
