# Generated by Django 5.0.4 on 2024-04-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_answers_answer_rename_attachments_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='round_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='round_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='round',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.quiz'),
        ),
    ]
