# Generated by Django 5.0.4 on 2024-04-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_round_description_round_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='ACTIVE', max_length=20)),
                ('score', models.PositiveSmallIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='quiz.quiz')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
