# Generated by Django 5.0.4 on 2024-04-09 12:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.round'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 12, 35, 1, 675211, tzinfo=datetime.timezone.utc)),
        ),
    ]
