# Generated by Django 5.0.4 on 2024-04-09 20:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_game_question_number_alter_game_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='round',
            new_name='round_num',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='quiz',
            new_name='quizzes',
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 20, 39, 28, 246605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_q', to='quiz.round'),
        ),
    ]
