# Generated by Django 5.0.4 on 2024-04-13 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_result_quiz_remove_result_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 20, 51, 37, 173921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
