# Generated by Django 5.0.4 on 2024-04-18 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_genre_icon_alter_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('One_Time', 'One_Time')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 12, 51, 57, 683726, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('INVITED', 'Invited')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='battles', to='quiz.game')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='quiz.quiz')),
            ],
        ),
    ]
