# Generated by Django 5.0.4 on 2024-04-18 14:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_game_end_time_quiz_status_alter_game_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='games',
        ),
        migrations.AlterField(
            model_name='battle',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 14, 27, 19, 267891, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='battle',
            name='games',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='quiz.game'),
        ),
    ]
