# Generated by Django 5.0.4 on 2024-04-21 18:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_rename_quizzes_round_quiz_alter_game_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 18, 50, 39, 732541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('One_Time', 'One_Time')], default='New', max_length=20),
        ),
    ]
