INSERT INTO quiz_answers (id, answer, valid_answer, question_id)
VALUES (1, 'Avril Lavigne', true, 1),
       (2, 'Pink', false, 1),
       (3, 'Ashlee Simpson', false, 1),
       (4, 'Kelly Clarkson', false, 1),
       (5, 'Ночные Снайперы', false, 2),
       (6, 'Zемфира', false, 2),
       (7, 'Город 312', true, 2),
       (8, 'Anacondaz', false, 2),
       (9, 'Christina Aguilera', false, 3),
       (10, 'Beyoncé', false, 3),
       (11, 'Katy Perry', false, 3),
       (12, 'Britney Spears', true, 3),
       (13, 'Звери', true, 4),
       (14, 'Animal ДжаZ', false, 4),
       (15, '7Б', false, 4),
       (16, 'Бумбокс', false, 4),
       (17, 'Robbie Williams', false, 5),
       (18, 'Mika', true, 5),
       (19, 'George Michael', false, 5),
       (20, 'Mark Ronson', false, 5),
       (21, 'Наутилус Помпилиус', false, 6),
       (22, 'Би-2', false, 6),
       (23, 'Сплин', true, 6),
       (24, 'Агата Кристи', false, 6),
       (25, 'Paul Van Dyk', true, 7),
       (26, 'Armin van Buuren', false, 7),
       (27, 'Tiesto', false, 7),
       (28, 'Ferry Corsten', false, 7),
       (29, 'Настя Каменских', false, 8),
       (30, 'Глюкоза', false, 8),
       (31, 'Юлия Савичева', false, 8),
       (32, 'Виктория Дайнеко', true, 8),
       (33, 'Paramore', true, 9),
       (34, 'Echosmith', false, 9),
       (35, 'We Are The In Crowd', false, 9),
       (36, 'Tonight Alive', false, 9),
       (37, 'Уматурман', true, 10),
       (38, '5''nizza', false, 10),
       (39, 'Lumen', false, 10),
       (40, 'Tracktor Bowling', false, 10),
       (41, '50 Cent', true, 11),
       (42, 'Зверев', true, 12),
       (43, 'Савичева', true, 13),
       (44, 'Kelly', true, 14),
       (45, 'Лазарев', true, 15),
       (46, 'Дельфин', true, 17),
       (47, 'Shakira', true, 18),
       (48, 'Пьеха', true, 19),
       (49, 'Timbaland', true, 20),
       (50, 'Animal ДжаZ - Три Полоски', true, 21),
       (51, 'Lumen - Государство', false, 21),
       (52, 'Ляпис Трубецкой - В платье белом', false, 21),
       (53, 'Noize MC - Артур Пирожков', false, 21),
       (54, 'Calvin Harris - Summer', false, 22),
       (55, 'Avicii - Levels', false, 22),
       (56, 'David Guetta - Titanium (feat. Sia)', false, 22),
       (57, 'Jakarta - One Desire', true, 22),
       (58, 'Rihanna – Bitch Better Have My Money', false, 23),
       (59, 'Beyonce - Green Light', true, 23),
       (60, 'Ciara – Like a Boy', false, 23),
       (61, 'Kelly Rowland – Work', false, 23),
       (62, 'Ida Corr & Fedde Le Grand - Let Me Think About It', true, 24),
       (63, 'Axwell – I Found U', false, 24),
       (64, 'Eric Prydz – Call on Me', false, 24),
       (65, 'Freemasons – Uninvited', false, 24),
       (66, 'Mark Ronson - Uptown Funk ft. Bruno Mars', false, 25),
       (67, 'OutKast - Hey Ya!', false, 25),
       (68, 'Madcon - Beggin', true, 25),
       (69, 'The Black Eyed Peas - Let''s Get It Started', false, 25),
       (70, 'Челси - Я к тебе не пойду', true, 26),
       (71, 'Глюк''oZa - Невеста', false, 26),
       (72, 'Zivert - ЯТЛ', false, 26),
       (73, 'Cream Soda - Никаких Больше Вечеринок', false, 26),
       (74, 'Dan Balan feat. Tany Vander & Brasco - Lendo Calen', false, 27),
       (75, 'DJ Project feat. Adela - Bun Ramas', false, 27),
       (76, 'Edward Maya feat. Vika Jigulina - Stereo Love', false, 27),
       (77, 'Morandi feat. Helene - Save Me', true, 27),
       (78, 'Елена Терлеева - Солнце', true, 28),
       (79, 'МакSим - Небо-самолеты', false, 28),
       (80, 'Ани Лорак - Солнце', false, 28),
       (81, 'Винтаж - Стерео', false, 28),
       (82, 'Martin Garrix & Matisse & Sadko - Forever', false, 29),
       (83, 'Eric Prydz vs. Pink Floyd - Proper Education', true, 29),
       (84, 'Swedish House Mafia - Don''t You Worry Child (feat.', false, 29),
       (85, 'Avicii - Levels', false, 29),
       (86, 'Breaking Benjamin - The Diary of Jane', false, 30),
       (87, 'Shinedown - Second Chance', false, 30),
       (88, 'Linkin Park - Numb', false, 30),
       (89, 'Three Days Grace - Never Too Late', true, 30),
       (90, 'Iglesias', true, 16);
